AA_DATABASE = {
    "A": {"nom": "Alanine","code": "ALA","masse_moleculaire": 89.09, "hydrophilicte": -0.5, "type": "neutre"},
    "R": {"nom": "Arginine","code": "ARG","masse_moleculaire": 174.20, "hydrophilicte": 3.0, "type": "base", "pKa": 12.5},
    "N": {"nom": "Asparagine","code": "ASN","masse_moleculaire": 132.12, "hydrophilicte": 0.2, "type": "neutre"},
    "D": {"nom": "Aspartate","code": "ASP","masse_moleculaire": 133.10, "hydrophilicte": 3.0, "type": "acide", "pKa": 3.9},
    "C": {"nom": "Cysteine","code": "CYS","masse_moleculaire": 121.15, "hydrophilicte": -1.0, "type": "acide", "pKa": 8.3},
    "Q": {"nom": "Glutamine","code": "GLN","masse_moleculaire": 146.15, "hydrophilicte": 0.2, "type": "neutre"},
    "E": {"nom": "Glutamate","code": "GLU","masse_moleculaire": 147.13, "hydrophilicte": 3.0, "type": "acide", "pKa": 4.1},
    "G": {"nom": "Glycine","code": "GLY","masse_moleculaire": 75.07, "hydrophilicte": 0.0, "type": "neutre"},
    "H": {"nom": "Histidine","code": "HIS","masse_moleculaire": 155.16, "hydrophilicte": -0.5, "type": "base", "pKa": 6.0},
    "I": {"nom": "Isoleucine","code": "ILE","masse_moleculaire": 131.17, "hydrophilicte": -1.8, "type": "neutre"},
    "L": {"nom": "Leucine","code": "LEU","masse_moleculaire": 131.17, "hydrophilicte": -1.8, "type": "neutre"},
    "K": {"nom": "Lysine","code": "LYS","masse_moleculaire": 146.19, "hydrophilicte": 3.0, "type": "base", "pKa": 10.5},
    "M": {"nom": "Methionine","code": "MET","masse_moleculaire": 149.21, "hydrophilicte": -1.3, "type": "neutre"},
    "F": {"nom": "Phenylalanine","code": "PHE","masse_moleculaire": 165.19, "hydrophilicte": -2.5, "type": "neutre"},
    "P": {"nom": "Proline","code": "PRO","masse_moleculaire": 115.13, "hydrophilicte": 0.0, "type": "neutre"},
    "S": {"nom": "Serine","code": "SER","masse_moleculaire": 105.09, "hydrophilicte": 0.3, "type": "neutre"},
    "T": {"nom": "Threonine","code": "THR","masse_moleculaire": 119.12, "hydrophilicte": -0.4, "type": "neutre"},
    "W": {"nom": "Tryptophane","code": "TRP","masse_moleculaire": 204.23, "hydrophilicte": -3.4, "type": "neutre"},
    "Y": {"nom": "Tyrosine","code": "TYR","masse_moleculaire": 181.19, "hydrophilicte": -2.3, "type": "acide", "pKa": 10.1},
    "V": {"nom": "Valine","code": "VAL","masse_moleculaire": 117.15, "hydrophilicte": -1.5, "type": "neutre"},
}